---
title: Introduction
output: 
   html_document:
    toc: true
    toc_depth: 1
--- 

## Overview
This tutorial describes how to run the IVI-RA model. The model is a discrete-time individual patient simulation (IPS) with 6-month model cycles that simulates patient outcomes over a lifetime or a specified time period. The model simulates the costs, health outcomes, and risks associated with disease-modifying anti-rheumatic drugs (DMARDs) and biologic DMARDSs (bDMARDs) for patients with moderate to severe rheumatoid arthritis. The primary measure of disease burden is the health assessment questionnaire (HAQ) score, which is a measure of function among patients with rheumatoid arthritis. 

The model accounts for both parameter and structural uncertainty. Parameter uncertainty is quantified using probabilistic sensitivity analysis (PSA), which propagates uncertainty in input parameters throughout the model by randomly sampling the parameters from their (joint) probability distribution and running the model for each sampled parameter set. Unlike most models, the IVI-RA model does not commit to a single model structure, but instead allows for a number of scientifically defensible approaches. Since the model can be run for any of the model structures, structural uncertainty can be evaluated by comparing estimates of value across the different structures. 

Users wishing to learn more about the model should consult the [model description](https://innovationvalueinitiative.github.io/IVI-RA/model-description/model-description.pdf).  

## Installation
The `iviRA` package can be installed from GitHub using the `devtools` package.

```r
# install.packages("devtools")
library(devtools)
devtools::install_github("InnovationValueInitiative/IVI-RA")
```

## Usage
To use the model, load the installed package into R.

```r
library(iviRA)
```

The model can be simulated within the `iviRA` package using the `sim_iviRA` function. The simulation depends on three primary factors: (1) the population considered, (2) the selected model structures, and (3) the values of the parameters. The steps needed to run the model and perform a value assessment can consequently be summarized as follows:

1. Generate a patient population
2. Select treatment arms
3. Select model structures
4. Generate model input data
5. Sample parameters related to input data
6. Simulate costs, health outcomes, and risks using the IPS
7. Perform value assessment 

## Continue tutorial
Click next to continue the tutorial and learn about step 1.  

<div>
<ul class="pager">
  <li class="next"><a href="01-population.html">Next</a></li>
</ul>
</div>