---
title: Using the IPS to simulate disease progression
output: 
   html_document:
    toc: true
    toc_depth: 1
--- 

```{r include=FALSE}
library("iviRA")
load("output.RData")
```

## Generate input data
```{r, cache = TRUE }
input.dat <- get_input_data(patdata = pop, model_structure = mod.struct)
```

## Run the IPS
Disease progression depends on the therapies used by patients. The list of potential therapies is available in the object `therapy.pars`, which contains all parameters in the model that vary across therapies.

```{r }
sim.out1 <- sim_iviRA(arms = arm1, input_data = input.dat, pars = parsamp,
                     model_structure = mod.struct)
sim.out1[, arm := "Arm 1"]
sim.out2 <- sim_iviRA(arms = arm2, input_data = input.dat, pars = parsamp,
                     model_structure = mod.struct)
sim.out2[, arm := "Arm 2"]
sim.out <- rbind(sim.out1, sim.out2)
```


<div>
<ul class="pager">
  <li class="previous"><a href="04-parameters.html">Previous</a></li>
  <li class="next"><a href="06-cea.html">Next</a></li>
</ul>
</div>

```{r include=FALSE}
save.image("output.RData")
```