---
title: Contribute to the model
output: 
   html_document:
    toc: true
    toc_depth: 1
---

There are two ways to collaborate with IVI. First, you can comment on the structure of the model or the evidence considered at [url]. IVI and a technical panel will review the comments and determine whether they should be incorporated into the model. Second, you can make changes to the code itself and make a [pull request](https://help.github.com/articles/about-pull-requests/). Code changes that affect the structure of the model or parameter values will only be incorporated after a review by the technical panel but other changes such as bug fixes or performance improvements may be immediately accepted. 

The purpose of this page is to help you make changes to the code. We use [Git](https://git-scm.com/) and host our code on [GitHub](https://github.com/). To collaborate, you will therefore need to create a GitHub account and [install](https://help.github.com/articles/set-up-git/) Git on your machine. Once your setup you can then follow the steps outlined below to contribute to the model.

**Step 1**: After signing into [GitHub](https://github.com/), you need to create your own remote repository of the IVI model. Click the "Fork" button  in the upper right corner of the [IVI-RA Github](https://github.com/InnovationValueInitiative/IVI-RA) page. When asked "Where should we fork this repository?" select your username.

**Step 2**: Use the command line to create a directory where you would like your local repository to live, and navigate to this directory.

**Step 3**: Create a local repository by typing the following command into the command line:

	git clone https://github.com/[github-username]/IVI-RA.git

**Step 4**: Use the command line to navigate to the local IVI-RA directory.

**Step 5**: In order to make it easier to [Push](https://help.github.com/articles/github-glossary/#push) your local work and [pull](https://help.github.com/articles/github-glossary/#pull) changes made by others to the IVI-RA code type the following command into the command line:

	git remote add upstream https://github.com/InnovationValueInitiative/IVI-RA.git

**Step 6**: Before editing your local copy of the IVI-RA code, make sure you have the latest version of the code using the following three commands:

+ Step 6a: Download all content from the central IVI-RA repository. Navigate to your local IVI-RA repository and type the following command into the command line:
	
		git fetch upstream
	
+ Step 6b: Switch to the master branch in your local IVI-RA repository by typing the following command into the command line:
	
		git checkout master
	
+ Step 6c: Update your local master IVI-RA branch to the latest version of the central IVI-RA master branch by using the [merge](https://help.github.com/articles/github-glossary/#merge) command:
	
		git merge upstream/master
	
**Step 7**: Create a new [branch](https://help.github.com/articles/github-glossary/#branch) on your local machine. Branches are a way to organize your project. To create a new branch type the following command into the command line:

	git checkout -b [new-branch-name]
	
**Step 8**: After making changes to your local IVI-RA repository, [commit](https://help.github.com/articles/github-glossary/#commit) your changes to the central IVI-RA repository. To add a new file type the following command into the command file:

	git add [filename]
	
To commit the added file or an edited file type the following command into the command line:

	git commit -m "[description-of-the-changes-you-made]"
	
To find all files that were edited or new files that were created, but not yet committed, type the following command into the command line:

	git status
	
**Step 9**: Periodically check whether the branch created in Step 7 is in sync with changes made by other contributors by fetching upstream and merging upstream master into your branch:

	git fetch upstream
	git merge upstream/master

If the changes you made to your local branch are in the same section as changes made by other contributors, you may need to resolve conflicts. 

**Step 10**: If the code is ready to be reviewed by other contributors, make a final commit and push your local branch to your remote repository:

	git push origin [new-branch-name]
	
**Step 11**: Using the GitHub user interface, [open a pull request](https://help.github.com/articles/creating-a-pull-request/#creating-the-pull-request).
