---
title: "Suggested model improvements"
output: html_document
---

The IVI-RA model is an iterative open-source model that is updated based on evidence-based suggestions for improvement. 

This page summarizes the suggested improvements that we have received from the public. Suggestions are separated into those that can be incorporated quickly (i.e., short-term) and those that involve data acquisition, more involved analyes, or large changes to the current code base (i.e., long-term). Code related issues with the model can be found on GitHub [here](https://github.com/InnovationValueInitiative/IVI-RA/issues).

The suggestions will be reviewed by the technical expert panel, which will prioritize and recommend improvements to incorporate into the next version of the model. Suggested improvements that are not incorporated into the model due to time or resource constraints will remain on this page and will be considered during future model updates. 

## Short-term suggestions
To be added during the public comment period.

## Long-term suggestions
To be added during the public comment period.