---
title: "Ways to contribute"
output: html_document
---

### Two ways to collaborate
There are two ways to collaborate with IVI. 

1. You can comment on the scientific approach or evidence considered at [url]. IVI and a technical panel will review the comments and determine whether they should be incorporated into the model. A synthesis of the comments we have received can be found [here](suggested-improvements.html). 

2. You can make changes to the code itself by making a [pull request](https://help.github.com/articles/about-pull-requests/). Code changes that affect the scientific approach or evidence considered will only be incorporated after a review by the technical panel but other changes such as bug fixes or performance improvements may be immediately accepted. Information on how to make a pull request is available [here](pull-requests.html).

### IVI model releases
New releases of the IVI-RA model follow the paradigm [described](http://r-pkgs.had.co.nz/release.html) by Hadley Wickham. Package versions follow the format `major.minor.patch`.

- **Patch**: A patch is a bug fix without any significant new features (e.g., `1.0.1`).

- **Minor release**: A minor release includes bug fixes or significant new features like a speed improvement (e.g., `1.1.0`).

- **Major release**: A major release involves a change to the scientific approach or evidence considered (e.g, `2.0.0`).

Patches and minor releases do not need to be reviewed by the technical expert panel and can be implemented through pull requests. Major releases only occur after improvements have been recommended by the panel. 